import { ComponentType } from "react";
import {
  ArrowRight,
  Baby,
  Book,
  Camera,
  Car,
  Coffee,
  Cpu,
  Dumbbell,
  Gamepad2,
  Hammer,
  Headphones as HeadphonesIcon,
  Home as HomeIcon,
  Laptop,
  Monitor,
  Music,
  Package,
  Shirt,
  Smartphone,
  Watch,
  Wrench,
  Zap,
} from "lucide-react";

const iconMap: Record<string, ComponentType<{ className?: string }>> = {
  electronics: Monitor,
  phones: Smartphone,
  smartphones: Smartphone,
  laptops: Laptop,
  computers: Monitor,
  cameras: Camera,
  watches: Watch,
  gaming: Gamepad2,
  headphones: HeadphonesIcon,
  audio: HeadphonesIcon,
  cpu: Cpu,
  computer: Monitor,
  fashion: Shirt,
  clothing: Shirt,
  shirts: Shirt,
  apparel: Shirt,
  wearables: Watch,
  accessories: Package,
  jewelry: Package,
  bags: Package,
  home: HomeIcon,
  furniture: HomeIcon,
  garden: HomeIcon,
  kitchen: HomeIcon,
  decor: HomeIcon,
  appliances: Zap,
  sports: Dumbbell,
  fitness: Dumbbell,
  gym: Dumbbell,
  exercise: Dumbbell,
  outdoor: Car,
  tools: Hammer,
  hardware: Wrench,
  diy: Hammer,
  repair: Wrench,
  baby: Baby,
  kids: Baby,
  toys: Gamepad2,
  books: Book,
  media: Book,
  education: Book,
  music: Music,
  entertainment: Gamepad2,
  food: Coffee,
  beverage: Coffee,
  drinks: Coffee,
  general: Package,
  miscellaneous: Package,
  other: Package,
  default: Package,
};

const normalize = (value?: string) => (value ? value.toLowerCase() : "default");

export function getCategoryIcon(categoryName: string, className: string = "h-8 w-8 text-primary") {
  const Icon = iconMap[normalize(categoryName)] || iconMap.default;
  return <Icon className={className} />;
}
